variable "aws_region" {
  description = "AWS region to deploy into"
  type        = string
  default     = "us-east-1"
}

variable "aws_access_key" {
  description = "AWS Access Key"
}

variable "aws_secret_key" {
  description = "AWS Secret Key"
}
variable "project_name" {
  description = "Name prefix used for tagging and naming all resources"
  type        = string
  default     = "django-app"
}

variable "environment" {
  description = "Deployment environment (e.g. dev, staging, prod)"
  type        = string
  default     = "dev"
}

# ---------------- Networking ----------------

variable "vpc_cidr" {
  description = "CIDR block for the VPC"
  type        = string
  default     = "10.0.0.0/16"
}

variable "azs" {
  description = "Availability zones to spread subnets across (must match subnet CIDR list length)"
  type        = list(string)
  default     = ["us-east-1a", "us-east-1b"]
}

variable "public_subnet_cidrs" {
  description = "CIDR blocks for public subnets (ALB tier)"
  type        = list(string)
  default     = ["10.0.0.0/24", "10.0.1.0/24"]
}

variable "private_app_subnet_cidrs" {
  description = "CIDR blocks for private application subnets (EC2 / nginx+django tier)"
  type        = list(string)
  default     = ["10.0.10.0/24", "10.0.11.0/24"]
}

variable "private_db_subnet_cidrs" {
  description = "CIDR blocks for private database subnets (RDS tier, no internet route at all)"
  type        = list(string)
  default     = ["10.0.20.0/24", "10.0.21.0/24"]
}

# ---------------- Compute (EC2 / ASG / ALB) ----------------

variable "instance_type" {
  description = "EC2 instance type for the application tier"
  type        = string
  default     = "t3.micro"
}

variable "asg_min_size" {
  type    = number
  default = 1
}

variable "asg_max_size" {
  type    = number
  default = 2
}

variable "asg_desired_capacity" {
  type    = number
  default = 1
}

variable "app_container_image" {
  description = "Django app container image (ECR URI or registry image:tag)"
  type        = string
  default     = "stevenjugunakamau/orderlee:dev"
}

variable "nginx_container_image" {
  description = "Nginx reverse proxy container image"
  type        = string
  default     = "nginx:1.27-alpine"
}

variable "acm_certificate_arn" {
  description = "Optional ACM certificate ARN. If set, an HTTPS listener is added to the ALB."
  type        = string
  default     = ""
}

# ---------------- Database (RDS) ----------------

variable "db_engine_version" {
  description = "PostgreSQL engine version"
  type        = string
  default     = "16.4"
}

variable "db_instance_class" {
  type    = string
  default = "db.t3.micro"
}

variable "db_allocated_storage" {
  description = "Initial storage (GB); autoscaling storage grows up to 5x this"
  type        = number
  default     = 20
}

variable "db_name" {
  type    = string
  default = "appdb"
}

variable "db_username" {
  description = "Master username for RDS. The password itself is generated by Terraform and never set here."
  type        = string
  default     = "djangoadmin"
}

variable "db_multi_az" {
  description = "Enable Multi-AZ RDS deployment"
  type        = bool
  default     = false
}

# ---------------- Bastion Server SSH Key ----------------

variable "aws_ssh_admin_key_file" {
  default     = "keys/aws_terraform"
  description = "AWS SSH key file path"
}

# ---------------- AfricasTalking Configs ----------------

variable "at_username" {
  type        = string
  description = "Africa's Talking Username"
  default     = "sandbox"
}

variable "at_api_key" {
  type        = string
  description = "Africa's Talking API Key"
  sensitive   = true
}

variable "at_sms_shortcode" {
  type        = string
  description = "Africa's Talking SMS Shortcode"
  default     = "3393"
}

# ---------------- Backend Configs ----------------

variable "django_admin_username" {
  type        = string
  description = "Django Super Admin Username"
  default     = "admin"
}

variable "django_admin_email" {
  type        = string
  description = "Django Super Admin Email"
  default     = "admin@gmail.com"
}

variable "debug" {
  type        = bool
  description = "Enable or disable Django DEBUG mode"
  default     = true
}

variable "allowed_hosts" {
  type        = list(string)
  description = "List of allowed hosts for Django"
  default     = ["localhost", "127.0.0.1"]
}

# ---------------- Bastion Server Allowed IP Range ----------------

variable "bastion_allowed_cidr_blocks" {
  type        = list(string)
  description = "CIDR blocks allowed to SSH into the Bastion"
  default     = ["0.0.0.0/0"] # Specific IP recommended for a production environment i.e office internal network
}